export const ACTION_TYPE = {
  SET_USER: 'SET_USER',
  LOG_OUT: 'LOG_OUT',
  SAVE_USER_ROLE: 'SAVE_USER_ROLE',
  SET_POST: 'SET_POST',
  ADD_COMMENT: 'ADD_COMMENT',
  REMOVE_COMMENT: 'REMOVE_COMMENT',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  DELETE_POST: 'DELETE_POST',
};
